export enum mongodbDataTypes {
    double = "double",
    string = "string",
    object = "object",
    array = "array",
    binData = "binData",
    undefined = "undefined",
    objectId = "objectId",
    bool = "bool",
    date = "date",
    null = "null",
    regex = "regex",
    dbPointer = "dbPointer",
    javascript = "javascript",
    symbol = "symbol",
    javascriptWithScope = "javascriptWithScope",
    int = "int",
    timestamp = "timestamp",
    long = "long",
    decimal = "decimal",
    minKey = "minKey",
    maxKey = "maxKey",
}
